* Project

Project requires submission of
-   .ipynb notebook  file  and a compiled pdf file. There must be a Binderhub link for running the notebook in github.
- Or if you are using cloud for building you project then a link to the website/details about running the project and a final project report pdf file. 

Final pdf file/notebook, should read like a data driven story/scientific study (data science). This is really important if you want to publish you story as 
blog in the web. There are tool to publish notebook as blog article.

Final project report(notebook or pdf) must address following points

** Questions, Dataset and motivation section.(2 point)
    What real world problems you are trying to solve. Dataset acquisition details. *What is the input and output of your analysis.*

** Quality of cleaning (3 points, 1 points each)
 - Data Cleaning and type conversion activity. 
 - What you did about missing values and  why?
 - Data summary statistics and interpretation.

** Visualization (4 points, 1 points each)
  - Data Visualization activity(box plot, bar plot, violin plot, pairplot to see relationship and distribution etc).
  - Describe any thing you find in the data after each visualization.
  - What data  visualization help you understanding data distribution.
  - What did you do about possible outlier as per data distribution visualization. (Did you confirm it with your client if it is actually an outlier or put a disclosure statement in notebook if you decided to remove it.)

** Modelling activity/evaluation/conclusion (5 points equally distributed in following 2 question depending on whether you are building a model or not) 
  + *if you are bulid a  model like logistic/linear regression* (3 points, 1 point each)
   
    + What kind of hypothesis you tested about predictors(independent variables).
    + Detail about model selection and evaluation activities.  
    + Model parameter/coefficient interpretation and their error analysis in context of research question.

  + *If you are building analytical website.* 
    + Describe Main Dash board, webpage with images.(1 point)
    + For at least one analytical/machine learning visualization(2 points,  1 point each)
      * Webpage/form to enter and submit new data points. After submitting the data webpage graphics must change to reflect new observation effect on graphics.
    + Any KPIs visualization and interpretation ?
** Conclusion (2 points)
   What is the final analysis of questions based on project activities.






